version: '3.8'
services:
    algo_node_mainnet:
        container_name: mainnet
        profiles: [ "mainnet" ]
        build:
            context: .
            dockerfile: node_mainnet.DockerFile
        volumes:
            - node_interface_shared_volume:/shared_volume/
            - ./config/config.json:/root/node/data/config.json

        stdin_open: true
        tty: true
        expose:
            - "8080"
    algo_node_testnet:
        container_name: testnet
        profiles: [ "testnet" ]
        build:
            context: .
            dockerfile: node_testnet.DockerFile
        volumes:
            - node_interface_shared_volume:/shared_volume/
            - ./config/config.json:/root/node/data/config.json
        stdin_open: true
        tty: true
        expose:
            - "8080"
    interface_server:
        profiles: [ "testnet", "mainnet" ]
        build:
            context: .
            dockerfile: interface_server.Dockerfile
        volumes:
            - node_interface_shared_volume:/shared_volume/
        stdin_open: true
        tty: true
        expose:
            - "42069"
    nginx:
        container_name: nginx
        profiles: [ "testnet", "mainnet" ]
        image: nginx:latest
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "4000:4000"

volumes:
    node_interface_shared_volume:
